/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package SpringBootSec;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;

public class App {
    public String getGreeting() {
	BCryptPasswordEncoder e = new BCryptPasswordEncoder();
	return e.encode("jinnai0");
    }

    public static void main(String[] args) {
	String pw;
	Boolean b;
	BCryptPasswordEncoder e = new BCryptPasswordEncoder();
        System.out.println(pw = new App().getGreeting());
	b = e.matches("jinnai0", pw);
	System.out.println("b=" + b);
    }
}
