server:
  port: 8080
spring:
  profiles: docker-compose
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db:3306/test_db
    username: docker
    password: pass
  jpa:
    database: test_db
    hibernate:
      ddl-auto: update
security:
    basic:
        enabled: false
