server:
  port: 8080
spring:
  profiles: docker-compose
  datasource:
    url: jdbc:mysql://db/tes_db
    username: docker
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
