server:
  port: 8080
spring:
  profiles: docker-compose
  datasource:
    url: jdbc:mysql://db:3306/db
    username: docker
    password: pass
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
security:
    basic:
        enabled: false
